### ISSUE TITLE
Build fails on i386 systems: error: no matching function for call to 'make_ul'

### ISSUE THREAD

**Issue by yurivict** [Smattr/rumur#136]
See the log here: http://beefy5.nyi.freebsd.org/data/120i386-default/503690/logs/rumur-2019.06.05.log

**Comment by Smattr** [comment]
Thanks for reporting this. Looks like the code incorrectly assumes `size_t` is the same as `unsigned long`. I don't have an i386 machine on which to reproduce this, but I've pushed some changes to the branch bugfix/github-136 that I think should resolve the problem. It hasn't passed Travis CI yet, but could you have a look at the changes in that branch and let me know if they solve your problem?

**Comment by yurivict** [comment]
I don't have an ```i386``` system either, and wouldn't be able to test it.

If you found some obvious problem, please just merge the fix and it will be auto-tested with the next port update.

**Comment by Smattr** [comment]
Hm a little awkward. I'll see if I have a platform that can bring up an i386 FreeBSD VM to test. Stay tuned...

**Comment by Smattr** [comment]
I brought up an i386 FreeBSD 12 VM and b04ecbc does indeed fix the compilation error. Unfortunately this unmasks the next problem.

The test suite fails because compilation of the generated verifier includes calls to undefined functions `__atomic_store_8` and `__atomic_load_8`. This is a situation I'm familiar with, where the compiler is expecting you to link against libatomic. However, the verifier is intended to be standalone (e.g. we pass `-mcx16` on x86_64 to force 128-bit operations to be emitted as `cmpxchg16b`, avoiding the libatomic call).

I tried to get Clang to emit a `cmpxchg8b` instead of the libatomic calls, using `-march=i586` and upgrading to Clang 8.0.0, but with no success. So I went digging for some details. It seems this problem was independently discovered during RC testing of LLVM on FreeBSD 11 (https://lists.llvm.org/pipermail/llvm-dev/2018-August/125090.html). The general consensus seems to be that the upstream in change in LLVM is actually a correction, but this doesn't help FreeBSD much whose tale seems to lead to this: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=230888.

I'm not sure what the best solution here is, as it seems libatomic is not available on FreeBSD and Rumur's generated verifier relies on double-word (64-bit on i386) atomics. We could work around this by taking a mutex, but it would be sort of self-defeating as the purpose of the atomics is to support a lock-free algorithm. As I can't imagine anyone using an i386 machine for the kind of memory-/runtime-intensive verification that Rumur is designed for, I'm inclined to just note we don't support i386 and leave it at that. What do you think?

**Comment by yurivict** [comment]
```libatomic``` might be unavailable by mistake.
There are some ports tat are disabled specifically on ```i386``` for a similar/same reason:
```
astro/siril/Makefile:BROKEN_i386=       undefined reference to `__atomic_load' and `__atomic_compare_exchange'
science/cctbx/bootstrap.pyscience/gromacs/Makefile:BROKEN_i386=   undefined reference to `__atomic_load' and `__atomic_compare_exchange'
science/qmcpack/Makefile:BROKEN_i386=     undefined reference to `__atomic_load'
science/gabedit/Makefile:BROKEN_i386=   undefined reference to `__atomic_load'
science/openmx/Makefile:BROKEN_i386=    undefined reference to `__atomic_load', see bug#229605 and https://reviews.llvm.org/D42154
science/erkale/Makefile:BROKEN_i386=    liberkale_omp.so.0.1.0: undefined reference to `__atomic_compare_exchange'
```

And there's this bug report: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=230888

So I suggest to label ```rumur``` likewise broken on i386 until this problem is resolved in the system.

**Comment by yurivict** [comment]
Please commit your fixes up to the point of this libatomic-related.

The port is already labeled BROKEN on i386.

**Comment by Smattr** [comment]
I toyed with this some more and discovered it's reproducible on non-FreeBSD platforms as well (at least macOS). If you do a 64-bit `__atomic_*` you end up with calls to `___atomic_*_8` in the emitted code when building with `-m32`. This all works out on macOS because Clang/LLVM itself provides these instead of relying on libatomic. Even so, this is undesirable as it makes this lock-free code no longer lock-free.

It seems we can force a `cmpxchg8` by using the older `__sync_*_compare_and_swap`. I think we should do this as we do for x86-64. I'll work on implementing this and see if it repairs FreeBSD i386 builds.

**Comment by Smattr** [comment]
I've just pushed a new release, v2019.06.12, that passes the test suite for me on FreeBSD i386. I'll wait for the Travis tests to pass and then tag the release commit.

**Comment by Smattr** [comment]
The tests passed and I've pushed the release tag. This should be everything to get the FreeBSD i386 port passing I think. Let me know if you have further problems, and thanks again for the packaging work!

**Comment by yurivict** [comment]
Thank you for fixing this issue!
I've just updated the port.
