### ISSUE TITLE
Unit test fail on smt-simplify.m

### ISSUE THREAD

**Issue by wangqr** [Smattr/rumur#140]
I am running `tests/integration-tests.py` in the v2019.06.30 release on Archlinux. I am using gcc 9.1.0, flex 2.6.4, and bison 3.3.2.

`tests/smt-simplify.m` is failing:
```
The following is the error trace for the error:

	/build/rumur/src/rumur-2019.06.30/tests/smt-simplify.m:18.6: read of undefined value in y within rule 1

Startstate 1 fired.
x:true
y:Undefined
```

And it seems that it only fails without valgrind.

**Comment by wangqr** [comment]
And the log:
https://gist.github.com/wangqr/f7f7de11aabf1e6ada59e8a829b04390

**Comment by Smattr** [comment]
Thanks for reporting.

The success with Valgrind is actually unrelated. The Valgrind tests [bail out before actually running the generated verifier](https://github.com/Smattr/rumur/blob/master/tests/integration-tests.py#L187-L192) because they're only checking for memory leaks in the rumur binary itself.

The failure you're seeing indicates that the [toy SMT solver](https://github.com/Smattr/rumur/blob/master/misc/toy-smt.py) failed to simplify a trivial expression, `y = y`. I suspect it is not being run correctly. Do you know what the command `python` resolves to in your environment? If you have the build directory available, could you let me know what is the output of `./rumur/rumur --output /dev/null --smt-simplification on --smt-path python --smt-arg <path to source dir>/misc/toy-smt.py --debug <path to source dir>/tests/smt-simplify.m`?

**Comment by wangqr** [comment]
```
$ python --version
Python 3.7.3
```
```
$ build/rumur/rumur --output /dev/null --smt-simplification on --smt-path python --smt-arg misc/toy-smt.py --debug tests/smt-simplify.m                                                                               [master*]
checking SMT problem:
(set-option :print-success false)
(set-logic QF_LIA)
(declare-const ru_x Bool)
(declare-const ru_y Bool)
(assert (not ru_y))
(check-sat)
failed to set SIGCHLD pipe non-blocking
SMT solver error
checking SMT problem:
(set-option :print-success false)
(set-logic QF_LIA)
(declare-const ru_x Bool)
(declare-const ru_y Bool)
(assert ru_y)
(check-sat)
failed to set SIGCHLD pipe non-blocking
SMT solver error
checking SMT problem:
(set-option :print-success false)
(set-logic QF_LIA)
(declare-const ru_x Bool)
(declare-const ru_y Bool)
(assert (not ru_y))
(check-sat)
failed to set SIGCHLD pipe non-blocking
SMT solver error
checking SMT problem:
(set-option :print-success false)
(set-logic QF_LIA)
(declare-const ru_x Bool)
(declare-const ru_y Bool)
(assert ru_y)
(check-sat)
failed to set SIGCHLD pipe non-blocking
SMT solver error
checking SMT problem:
(set-option :print-success false)
(set-logic QF_LIA)
(declare-const ru_x Bool)
(declare-const ru_y Bool)
(assert (not ru_x))
(check-sat)
failed to set SIGCHLD pipe non-blocking
SMT solver error
checking SMT problem:
(set-option :print-success false)
(set-logic QF_LIA)
(declare-const ru_x Bool)
(declare-const ru_y Bool)
(assert ru_x)
(check-sat)
failed to set SIGCHLD pipe non-blocking
SMT solver error
checking SMT problem:
(set-option :print-success false)
(set-logic QF_LIA)
(declare-const ru_x Bool)
(declare-const ru_y Bool)
(assert (not (not ru_x)))
(check-sat)
failed to set SIGCHLD pipe non-blocking
SMT solver error
checking SMT problem:
(set-option :print-success false)
(set-logic QF_LIA)
(declare-const ru_x Bool)
(declare-const ru_y Bool)
(assert (not ru_x))
(check-sat)
failed to set SIGCHLD pipe non-blocking
SMT solver error
checking SMT problem:
(set-option :print-success false)
(set-logic QF_LIA)
(declare-const ru_x Bool)
(declare-const ru_y Bool)
(assert (not (= ru_y ru_y)))
(check-sat)
failed to set SIGCHLD pipe non-blocking
SMT solver error
checking SMT problem:
(set-option :print-success false)
(set-logic QF_LIA)
(declare-const ru_x Bool)
(declare-const ru_y Bool)
(assert (= ru_y ru_y))
(check-sat)
failed to set SIGCHLD pipe non-blocking
SMT solver error
considering type uint8_t...
using numerical type uint8_t as value type
```

**Comment by wangqr** [comment]
Sorry for left out the system information. I was running Archlinux on WSL1 on Windows 10.0.18362.207. And I checked that this issue does not happen on a real linux machine.

**Comment by Smattr** [comment]
Thanks! The debug log showed some surprising things and led me to what I think is the root cause. I made the classic mistake of using `F_SETFD` with `O_NONBLOCK` instead of `F_SETFL`. I've just committed 53f20cc00398eefd81a7a1d015517d3051b23548 which fixes this. Are you able to test with this commit and see if it fixes your problem?

**Comment by wangqr** [comment]
Yes, that commit does fix this issue.

**Comment by Smattr** [comment]
Excellent! Thanks for troubleshooting with me!
